name: build & release

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '3.0.0'
        
jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Will start a Maven Release using version ${{ github.event.inputs.releaseversion }}"

      - uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3.3.1
        env:
          cache-name: cache-mvn
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Set new SNAPSHOT version
        run: > 
          mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}" && \
            mvn  versions:set -DnextSnapshot && \
            VERSION=$(mvn exec:exec -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive -q) && \
            mvn versions:revert && \
            mvn versions:set-property -Dproperty=revision  -DnewVersion="$VERSION" &&
            mvn versions:commit
      
      - name: Check changes
        run: git status
      
      - name: Commit new SNAPSHOT version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.PAT }}
        
          
  publish-github-release:
    needs: publish-central-and-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.releaseversion }}
          release_name: ${{ github.event.inputs.releaseversion }}
          body: |
            Grab the new version from Maven central https://repo1.maven.org/maven2/de/codecentric/

            Current docs at https://codecentric.github.io/spring-boot-admin/${{ github.event.inputs.releaseversion }}/

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(github.event.inputs.releaseversion, '-') }}